# My Knowhow

## Neuroscience

[[RGC][Retinal ganglion cell (RGC)]] - neurons that collectively transmit image-forming and non-image forming visual information from the retina to several regions in the thalamus, hypothalamus, and mesencephalon, or midbrain.

