# Retinal ganglion cell

A retinal ganglion cell (RGC) is a type of neuron located near the inner surface (the ganglion cell layer) of the retina of the eye. 
It receives visual information from photoreceptors via intermediate neurons.
Retinal ganglion cells collectively transmit image-forming and non-image forming visual information from the retina to several regions in the thalamus, hypothalamus, and mesencephalon, or midbrain.

Retinal ganglion cells vary significantly in terms of their size, connections, and responses to visual stimulation but they all share the defining property of having a long axon that extends into the brain. 
These axons form the optic nerve, optic chiasm, and optic tract. 
A small percentage of retinal ganglion cells contribute little or nothing to vision, but are themselves photosensitive; their axons form the retinohypothalamic tract and contribute to circadian rhythms and pupillary light reflex, the resizing of the pupil.

